### ISSUE TITLE
Error with Report

### ISSUE THREAD

**Issue by peakers1976** [microsoft/AADConnectConfigDocumenter#23]
Hi,

I have downloaded the latest release, run the .CMD file on the sample Data from Contoso.

Issue i have.
- export config from AADConnect
- Copy config into separate folder under data 
- customise cmd file to point to new location Pilot folder.
- run the command file

System.Xml.XmlException: '.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ThrowInvalidChar(Char[] data, Int32 length, Int32 invCharPos)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlReader.MoveToContent()
   at System.Xml.Linq.XElement.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XElement.Load(String uri, LoadOptions options)
   at AzureADConnectConfigDocumenter.AzureADConnectSyncDocumenter.MergeConfigurationExports(Boolean pilotConfig)
   at AzureADConnectConfigDocumenter.AzureADConnectSyncDocumenter.MergeSyncExports()
   at AzureADConnectConfigDocumenter.AzureADConnectSyncDocumenter..ctor(String targetSystem, String referenceSystem)
   at AzureADConnectConfigDocumenter.Program.Main(String[] args)

**Comment by peakers1976** [comment]
All good it was because i didnt copy the config folders to both pilot and production.
