### ISSUE TITLE
System.IO.PathTooLongException - Error 40000

### ISSUE THREAD

**Issue by hich77** [Microsoft/AADConnectConfigDocumenter#8]
Hi,

we've a lot of connector connected inside our AADSync, and we wanted to use your application to allow us to create a staging mode server of our production, but we encounter that kind of problem : AADConnectSyncDocumenterConsole Information: 20000 : AADConnectSyncDocumenter (1.17.0703.0): 07/26/2017 10:14:46.6333:
Sync Rule Name: 'In from AD - CGUID does not exist (Create CGUID in metaverse + CloudFilter object until persisted in AD
)'.  Connector Category: 'AD'.  Connector Name: 'CAAMI-HZIV.INT'.  Connector Guid: '9330C63B-B4F2-4094-8A96-6AF0E4C79072
'.  Connector SubType: ''.  Sync Rule Report Type: 'ConditionalJoinSection'.  Sync Rule Guid: '0ec1c63e-8eea-48df-8733-8
baf20e1f559'. Processing changes. This may take a few minutes...
AADConnectSyncDocumenterConsole Error: 40000 : AADConnectSyncDocumenter (1.17.0703.0): 07/26/2017 10:14:46.6487:  Connec
tor SubType: ''. Exception in 'AzureADConnectSyncDocumenter : GetReport'. Details: System.IO.PathTooLongException: The s
pecified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the
directory name must be less than 248 characters.
   at System.IO.PathHelper.GetFullPathName()
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShar
e share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolea
n useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileO
ptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path)
   at AzureADConnectConfigDocumenter.SyncRuleDocumenter.WriteSyncRuleReportHeader()
   at AzureADConnectConfigDocumenter.SyncRuleDocumenter.GetReport(SyncRuleReportType reportType)
   at AzureADConnectConfigDocumenter.ConnectorDocumenter.ProcessConnectorSyncRules(SyncRuleDirection direction, SyncRule
ReportType reportType)
   at AzureADConnectConfigDocumenter.ConnectorDocumenter.ProcessConnectorNormalJoinSyncRules()
   at AzureADConnectConfigDocumenter.ActiveDirectoryConnectorDocumenter.GetReport()
   at AzureADConnectConfigDocumenter.AzureADConnectSyncDocumenter.ProcessConnectorConfiguration(XElement connector, Conf
igEnvironment configEnvironment)
   at AzureADConnectConfigDocumenter.AzureADConnectSyncDocumenter.ProcessConnectorConfigurations()
   at AzureADConnectConfigDocumenter.AzureADConnectSyncDocumenter.GetReport().

Unhandled Exception: System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qual
ified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at AzureADConnectConfigDocumenter.AzureADConnectSyncDocumenter.GetReport()
   at AzureADConnectConfigDocumenter.AzureADConnectSyncDocumenter.GenerateReport()
   at AzureADConnectConfigDocumenter.Program.Main(String[] args)

**Comment by NileshGhodekar** [comment]
Looks like Temp files path is getting too long. Can you put "SET TMP=%~dp0" as the first line in your AzureADConnectSyncDocumenter.cmd script and see if it helps? You should then see temp files getting generated in the documenter folder when the tool is running.

**Comment by hich77** [comment]
Hi Nilesh, 
I've tried with two times the same files inside my data folder, it run really fine without redirecting the temp folder.  Now i'm launching the script against my production configuration files, and my newly installed server.  Hope it could work ;-) 

Thanks a lot for your answer, i'm giving you the results of my test afterwards.

regards

**Comment by hich77** [comment]
Hi Nilesh, sorry for my late answer :-)

But everything is working fine now on my server as on my workstations !  It's a really nice tool, but i'm a little bit disappointed about the default rules that aren't created if the script create new connector that i've configured inside my pilot and i'm trying to automatically create inside my production server. 

Regards
